import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ul>
          <Link href="/"><li>Home</li></Link>
          <Link href="/Users"><li>User</li></Link>
          <Link href="/Contact"><li>Contact</li></Link>
        </ul>

        {children}

      
      </body>
    </html>
  );
}
